version: '2'
services:
  nginx:
          build: nginx
          container_name: Nginx
          ports:
              - "80:80"
          tty: true 
          
  pm2: 
        build: pm2
        container_name: PM2
        